services:
  besu:
    image: hyperledger/besu:25.3.0
    container_name: besu-node
    command:
      - --genesis-file=/config/genesis.json
      - --data-path=/var/lib/besu
      - --node-private-key-file=/var/lib/besu/key
      - --rpc-http-enabled=true
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-cors-origins=*
      - --rpc-http-api=ETH,NET,WEB3,CLIQUE
      - --host-allowlist=*
      - --min-gas-price=0
      - --miner-enabled=true
      - --miner-coinbase=0xf1702e1ca825ba2fb91c7d72015e98d9f03bca91
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./genesis.json:/config/genesis.json
      - ./node1:/var/lib/besu
